### ISSUE TITLE
wrong about url in sidebar

### ISSUE THREAD

**Issue by novolife** [artchen/hexo-theme-element#10]
in sidebar, the link to "about" should(maybe) be generate as `xx.com/about/`, but it becomes `xx.com/index.htmlabout`.
I looked into the layout(sidebar.ejs), there is `<a class="name dark-btn" href="<%- url_for() %>about">`, loos like the function `url_for()` returns the url for the page(`xx.com/index.html`) instead of `xx.com/`

**Comment by artchen** [comment]
Thanks for reporting the bug. Could you submit a pull request?

**Comment by novolife** [comment]
@artchen literally I'm not good at js or sth else in frontend and know little about hexo, cannot fix it in a proper way, but that would be ok if you need me to change the `url_for()` into '\'.

**Comment by artchen** [comment]
Changed to `url_for('/about')` in latest commit.
