### ISSUE TITLE
Hexo菜雞路過 請教預覽圖的問題

### ISSUE THREAD

**Issue by aaronlin0122** [artchen/hexo-theme-element#11]
如題 請問預覽圖該如何設置? 
![image](https://user-images.githubusercontent.com/47508893/86953436-05300400-c187-11ea-9fe1-1b6524fc97bb.png)

**Comment by NekoChan-2851** [comment]
小弟我使用markdown的插入圖片,也沒有預覽圖顯示
![](網址)
有辦法顯示預覽圖, 並在文章中隱藏圖片嗎?

**Comment by NekoChan-2851** [comment]
還是說無法顯示預覽圖 😕

**Comment by Saul-Mirone** [comment]
你是如何插入图片的？

**Comment by artchen** [comment]
不存在这个功能

**Comment by NekoChan-2851** [comment]
好的 感謝您的回覆👍
