### ISSUE TITLE
Problem applying the element theme

### ISSUE THREAD

**Issue by stefenlove** [artchen/hexo-theme-element#12]
I'm not sure whats going on I've download all the dependencies

system: ubuntu 20.04
node version: 12.18
npm version: 6.14

![Screenshot from 2020-09-06 22-46-59](https://user-images.githubusercontent.com/70869800/92344082-77439d00-f093-11ea-85b9-24efd9057be6.png)

location of blog: usr/local/bin/blog/
*dependencies where install outside of this folder due to permissions. It's not possible to test installing them from inside the folder. still the results are the same.
*I don't think any of the .scss or .ejs files are being used I'm not sure why.

Is there any other troubleshooting to do. Help. I want this theme.
Thanks!

**Comment by artchen** [comment]
Hi @stefenlove , I think ejs templates are definitely compiled but the styling is not applied. Could you check the following:

1. Are there errors in the browser console.
2. Is there a non-empty css file generated in the output folder.

**Comment by stefenlove** [comment]
@artchen 
This is what the console returns
The resource from “http://localhost:4000/style.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff)

**Comment by artchen** [comment]
> @artchen
> This is what the console returns
> The resource from “[http://localhost:4000/style.css”](http://localhost:4000/style.css%E2%80%9D) was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff)

Sounds like the style.css wasn't generated, did you modify the styles?

**Comment by stefenlove** [comment]
No i haven't. Where would it be located?

**Comment by artchen** [comment]
I re-read the post, I didn't realize that the dependencies were not installed inside the folder. I think you need to properly install the node dependencies for hexo to work in general, in other words, the required npm packages needs to show up in node_modules. Right now the issue likely due to the plugins weren't picked up.

**Comment by artchen** [comment]
In other words, I would recommend developing your theme in a directory where your user has write permission. For deploying the site, I recommend check out AWS Amplify or Netlify.

**Comment by stefenlove** [comment]
I want to clarify that only a few of the packages weren't installed by default and i had problems with permissions initially when trying to install them. 

I was able to resolve problems with permissions by reinstalling npm set to global
`npm install -g npm#version`

The **hexo-renderer-scss** was outputing errors even with npm set to global  

> hexo-renderer-scss was why it wasn't displaying correctly

### Resolve the errors manually 
I manually created a  /node-sass/vendor/linux-[YourVersion] directory `mkdir`. hexo-renderer-scss  was unable to save binary to this directory because it didn't exist.

To load hexo-renderer-scss i got the binding.node file for my system from here https://github.com/sass/node-sass/releases.

 Then moved the node file to /linux-[YourVersion] directory
`mv  FileName /DirectoryName` 

And renamed the node file         
`mv CurrentFileName binding.node`

I installed hexo-renderer-scss without scripts to stop the final conflicts
`npm install hexo-renderer-scss --ignore-scripts`

Then i retarted the hexo server

A-OK! Thanks @artchen
