### ISSUE TITLE
the email icon is missing 

### ISSUE THREAD

**Issue by kian98** [artchen/hexo-theme-element#8]
after setting the email url like mailto:xxxxx, there is no email icon in the sidebar
![image](https://user-images.githubusercontent.com/20855048/50082810-d6f97500-022c-11e9-9de5-d45a4dceb01a.png)

**Comment by kian98** [comment]
just add code to `/source/icomoon/style.css`  
```  
.icon-email:before {  
  content: "\e90d";  
}  
```

**Comment by artchen** [comment]
That was weird. The css class name should be `icon-mail` - I just searched in the repo and there is no `icon-email` anywhere.
